#!/usr/bin/env bash

# Creates all 1 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# VMware-NSX — This is the URL for the VMware NSX instance. It also includes an optional tenant in square brackets before the URL. A tenant value is required when the certificates being managed are in a different tenant from the default tenant set for the NSX User specified for the store. This should look like either: [optional-tenant-name]https://my.nsx.url/ OR https://my.nsx.url/ 
# ---------------------------------------------------------------------------
create_store_type "VMware-NSX" '{
  "Name": "VMware-NSX",
  "ShortName": "VMware-NSX",
  "Capability": "VMware-NSX",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ApiVersion",
      "DisplayName": "X-Avi-Version",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "20.1.1",
      "Required": true,
      "IsPAMEligible": false
    },
    {
      "Name": "RetriesForFailedAuthentication",
      "DisplayName": "Retries For Failed Authentication",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "0",
      "Required": false,
      "IsPAMEligible": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "MultipleChoice",
  "StorePathValue": "[\"Application\",\"Controller\",\"CA\"]",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "StorePathDescription": "A selection from the different certificate types supported: Application, Controller, or CA."
}'


echo "Completed."
